#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use CliFrame\App;
use CliFrame\CommandCall;

$app = new App();
$app->setSignature("cliFrame hello name [ user=name ]");

$app->registerCommand('help', function (CommandCall $call) use ($app) {
    $app->printSignature();
    print_r($call->params);
});

$app->runCommand($argv);
