#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use CliFrame\App;

$app = new App([
   'app_path' => __DIR__ . '/app/Command'
]);

$app->runCommand($argv);
